#!/usr/bin/env node
/** Copy the local `@pmndrs/sky` build into `vendor/pmndrs-sky`. */
import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const SOURCE =
  process.env.SKY_REPO ?? "/Users/dex/Developer/SebH-TSL-Sky";
const DEST = path.resolve(import.meta.dirname, "../vendor/pmndrs-sky");

const pkg = JSON.parse(
  await readFile(path.join(SOURCE, "package.json"), "utf8"),
);

// Keep only what a consumer resolves against.
const vendored = {
  name: pkg.name,
  version: pkg.version,
  description: pkg.description,
  license: pkg.license,
  type: pkg.type,
  sideEffects: pkg.sideEffects,
  main: pkg.main,
  module: pkg.module,
  types: pkg.types,
  exports: pkg.exports,
  peerDependencies: pkg.peerDependencies,
  peerDependenciesMeta: pkg.peerDependenciesMeta,
  _vendoredFrom: SOURCE,
  _vendoredNote:
    "Generated by scripts/sync-sky.mjs. Do not edit — edit the sky checkout and re-run `pnpm sync:sky`.",
};

await rm(DEST, { recursive: true, force: true });
await mkdir(DEST, { recursive: true });
await cp(path.join(SOURCE, "dist"), path.join(DEST, "dist"), {
  recursive: true,
});
await writeFile(
  path.join(DEST, "package.json"),
  JSON.stringify(vendored, null, 2) + "\n",
);

console.log(
  `[sync-sky] ${pkg.name}@${pkg.version} -> ${path.relative(process.cwd(), DEST)}`,
);
